#!/bin/bash -e
# regenerate mysql password  

. /etc/default/inithooks

PASSWORD=$(mcookie)

# messy aspnet config setup

aspnet_src_config=/var/www/aspnetcore-src/appsettings.json
aspnet_bin_config=/var/www/aspnetcore/appsettings.json
old_pword=$(jq -r '.ConnectionStrings.ExampleContext' $aspnet_src_config)
conn_string=$(echo $old_pword | sed "s/Password=[^;]*;/Password=$PASSWORD;/")
jq -M ".ConnectionStrings.ExampleContext = \"$conn_string\"" $aspnet_src_config > /tmp/tmp-appconfig
mv /tmp/tmp-appconfig "${aspnet_src_config}"
cp "${aspnet_src_config}" "${aspnet_bin_config}"

$INITHOOKS_PATH/bin/mysqlconf.py --user=aspnet --pass="$PASSWORD"

systemctl restart aspnetcore
